### ISSUE TITLE
GitHub Icons flickers

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass-website#1]
![jan-20-2017 09-30-12](https://cloud.githubusercontent.com/assets/932103/22153255/8bf96d42-def4-11e6-978b-7f17120ff5a6.gif)

**Comment by flekschas** [comment]
This seems to be loading issue. Better cache control could help (e.g., adding a unique number to every version of the file and caching it indefinitely)

Another option is to inline SVG icons at the top of every HTML page.

**Comment by pkerpedjiev** [comment]
Looks fixed in higlass.io. Closing.
